// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Utilities;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace UtilitiesTests
{
    /// <summary>
    ///This is a test class for Utilities.BaseArray and is intended
    ///to contain all Utilities.BaseArray Unit Tests
    ///</summary>
    [TestClass]
    public class BaseArrayTest
    {
        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext { get; set; }

        #region Additional test attributes

        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //

        #endregion

        /// <summary>
        ///A test for Current
        ///</summary>
        [TestMethod]
        public void CurrentTest()
        {
            var target = new BaseArray();
            Assert.AreEqual(0, target.Count(), "Utilities.BaseArray.Current was not set correctly.");
        }

        /// <summary>
        ///A test for DeleteAll ()
        ///</summary>
        [TestMethod]
        public void DeleteAllTest()
        {
            var target = new BaseArray();
            target.DeleteAll();
            Assert.AreEqual(0, target.Count(), "Utilities.BaseArray.Current was not set correctly.");
        }

        /// <summary>
        ///A test for DeleteRecord (int)
        ///</summary>
        [TestMethod]
        public void DeleteRecordTest()
        {
            var target = new BaseArray();
            const int nIndex = 0;
            target.DeleteRecord(nIndex);
            Assert.AreEqual(0, target.Count(), "Utilities.BaseArray.Current was not set correctly.");
        }

        /// <summary>
        ///A test for Count ()
        ///</summary>
        [TestMethod]
        public void GetCountTest()
        {
            var target = new BaseArray();
            Assert.AreEqual(0, target.Count(), "Utilities.BaseArray.Current was not set correctly.");
        }

        /// <summary>
        ///A test for GetEnumerator ()
        ///</summary>
        [TestMethod]
        public void GetEnumeratorTest()
        {
            var target = new BaseArray();
            Assert.AreEqual(0, target.Count(), "Utilities.BaseArray.Current was not set correctly.");
        }

        /// <summary>
        ///A test for MoveNext ()
        ///</summary>
        [TestMethod]
        public void MoveNextTest()
        {
            var target = new BaseArray();
            const bool expected = false;
            bool actual = target.MoveNext();
            Assert.AreEqual(expected, actual, "Utilities.BaseArray.MoveNext did not return the expected value.");
        }

        /// <summary>
        ///A test for Reset ()
        ///</summary>
        [TestMethod]
        public void ResetTest()
        {
            var target = new BaseArray();
            target.Reset();
            Assert.AreEqual(0, target.Count(), "Utilities.BaseArray.Current was not set correctly.");
        }
    }
}