// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Kfd.Tools;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace KfdToolsTests
{
    /// <summary>
    ///This is a test class for Kfd.Tools.Base64Decoder and is intended
    ///to contain all Kfd.Tools.Base64Decoder Unit Tests
    ///</summary>
    [TestClass]
    public class Base64DecoderTest
    {
        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext { get; set; }

        #region Additional test attributes

        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //

        #endregion

        /// <summary>
        ///A test for Base64Decoder (char[])
        ///</summary>
        [TestMethod]
        public void ConstructorTest()
        {
            char[] input = {'t', 'e', 's', 't'};
            var target = new Base64Decoder(input);
            Assert.AreEqual(input[0], target.GetSource()[0]);
        }

        /// <summary>
        ///A test for Char2SixBit (char)
        ///</summary>
        [TestMethod]
        public void Char2SixBitTest()
        {
            const char c = 't';
            const byte expected = 45;
            byte actual = Base64Decoder.Char2SixBit(c);
            Assert.AreEqual(expected, actual, "Kfd.Tools.Base64Decoder.Char2SixBit did not return the expected value.");
        }

        /// <summary>
        ///A test for GetDecoded ()
        ///</summary>
        [TestMethod]
        public void GetDecodedTest()
        {
            char[] input = {'t', 'e', 's', 't', '\0'};
            var target = new Base64Decoder(input);
            byte[] expected = {181, 235, 45};
            byte[] actual = target.GetDecoded();
            CollectionAssert.AreEqual(expected, actual, "Kfd.Tools.Base64Decoder.GetDecoded did not return the expected value.");
        }
    }

    /// <summary>
    ///This is a test class for Kfd.Tools.Base64Encoder and is intended
    ///to contain all Kfd.Tools.Base64Encoder Unit Tests
    ///</summary>
    [TestClass]
    public class Base64EncoderTest
    {
        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext { get; set; }

        #region Additional test attributes

        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //

        #endregion

        /// <summary>
        ///A test for Base64Encoder (byte[])
        ///</summary>
        [TestMethod]
        public void ConstructorTest()
        {
            byte[] input = {64, 65, 66};
            var target = new Base64Encoder(input);
            Assert.AreEqual(input, target.GetSource());
        }

        /// <summary>
        ///A test for GetEncoded ()
        ///</summary>
        [TestMethod]
        public void GetEncodedTest()
        {
            byte[] input = {64, 65, 66};
            var target = new Base64Encoder(input);
            char[] expected = {'Q', 'E', 'F', 'C'};
            char[] actual = target.GetEncoded();
            CollectionAssert.AreEqual(expected, actual, "Kfd.Tools.Base64Encoder.GetEncoded did not return the expected value.");
        }

        /// <summary>
        ///A test for SixBit2Char (byte)
        ///</summary>
        [DeploymentItem("KFDTools.dll")]
        [TestMethod]
        public void SixBit2CharTest()
        {
            const byte b = 64;
            const char expected = ' ';
            char actual = Base64Encoder.SixBit2Char(b);
            Assert.AreEqual(expected, actual, "Kfd.Tools.Base64Encoder.SixBit2Char did not return the expected value.");
        }
    }
}