// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Utilities;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
namespace UtilitiesTests
{
    /// <summary>
    ///This is a test class for Utilities.StateCodes and is intended
    ///to contain all Utilities.StateCodes Unit Tests
    ///</summary>
    [TestClass()]
    public class StateCodesTest
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for GetCode (string)
        ///</summary>
        [TestMethod()]
        public void GetCodeTest()
        {
            Assert.IsTrue(StateCodes.GetCode(null) == null);
            Assert.IsTrue(StateCodes.GetCode("") == null);
            Assert.IsTrue(StateCodes.GetCode("Guam").Equals("GU"));
            Assert.IsTrue(StateCodes.GetCode("gUaM").Equals("GU"));
        }

        /// <summary>
        ///A test for GetName (string)
        ///</summary>
        [TestMethod()]
        public void GetNameTest()
        {
            Assert.IsTrue(StateCodes.GetName(null) == null);
            Assert.IsTrue(StateCodes.GetName("") == null);
            Assert.IsTrue(StateCodes.GetName("GU").Equals("Guam"));
            Assert.IsTrue(StateCodes.GetName("gU").Equals("Guam"));
        }

        /// <summary>
        ///A test for indexOf (string)
        ///</summary>
        [DeploymentItem("Utilities.dll")]
        [TestMethod()]
        public void IndexOfTest()
        {
            string code = "Guam"; 
            int expected = 16;
            int actual = StateCodes_Accessor.indexOf(code);
            Assert.AreEqual(expected, actual, "Utilities.StateCodes.indexOf did not return the expected value.");
        }
    }
}
